[package]
name = "carrier"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
flate2 = "1.1.2"
futures-util = "0.3"
indicatif = "0.18.0"
lazy_static = "1.5.0"
reqwest = { version = "0.12.23", features = ["blocking", "json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
tar = "0.4.44"
tokio = { version = "1", features = ["full"] }
